### ISSUE TITLE
support for all browsers, ES6 generator , Weakmap

### ISSUE THREAD

**Issue by jscsharp** [likr/eg-graph#1]
Hi
Is it possible to  compile the code to ES5? to able to run on all browsers.

Thanks

**Comment by likr** [comment]
Thanks, but I don't provide compiled code from this repository.
Please use babel in your application.

For example, webpack setting with babel-loader is as follows:

```javascript
module.exports = {
  module: {
    loaders: [
      {
        test: /\.jsx?$/,
        include: [
          path.resolve(__dirname, 'src'),
          path.resolve(__dirname, 'node_modules/egraph')
        ],
        loader: 'babel-loader',
        query: {
          presets: ['latest'],
          plugins: ['transform-react-jsx']
        }
      }
    ]
  },
  // ...
}
```

**Comment by jscsharp** [comment]
Thanks, for your reply. I will test it.

**Comment by jscsharp** [comment]
I made es5 compilation using webpack, babel. But for WeakMap usage in the code, IE11 does not support it, as mention here:
https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/WeakMap

Is this  good option  to use following code to polyfill WeakMap in IE11 or older browsers which does not support WeakMap?
https://github.com/Benvie/WeakMap

Thanks

**Comment by likr** [comment]
You can use babel-polyfill.
see: https://babeljs.io/docs/usage/polyfill/

**Comment by jscsharp** [comment]
Thanks a lot.
