### ISSUE TITLE
Converting the project to Typescipt.

### ISSUE THREAD

**Issue by jscsharp** [likr/eg-graph#2]
I wanted to convert the project to  Typescipt project . so I did following steps:

Typescirpt added the Generators and Iteration for ES5/ES3:
Please see here:
https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript
so install latest tsc compiler:
1) npm install -g typescript@next 

2) remove the Test folder for now

3) In Windows command line: Rename all  js files in folder and  its subfolder from js to ts, via command line:
c:>home2/egraph_typescript>FOR /R %f IN (*.js) DO REN "%f" *.ts

4) add tsconfig.json in root folder with following content:

{
  
  "compilerOptions": {
       "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
  
    
   
    "moduleResolution": "node",
    "removeComments": true,
    "sourceMap": false
  },
  "exclude": [
    "node_modules"
  ]
}

5) npm install  and run tsc compiler  from command line:

  c:>home2/egraph_typescript> tsc

Tsc compiler can generate ES5 output and it seems, the final file size is smaller that using Babel which I did and asked you about it before. But it still needs WeakMap polyfill.

Please let me know what is your thought?

Thanks

**Comment by likr** [comment]
Sorry, I don't plan to convert egraph to TypeScript.
